export const earthConfig = {
  mass: 1,
  radius: 1,
  temperature: 288,
  surfaceRoughness: 0.65,
  terrainErosion: 0.4,
  waterLevel: 0.65,
  biomassLevel: 0.7,
  plateTectonics: 0.8,
  soilType: "organic",
  soilTexture: "layered",
  atmosphereStrength: 0.8,
  liquidType: "water",
  salinity: 0.35,
  precipitationCompound: "water",
  biome: "Temperate Forest",
  mountainHeight: 0.7,
  hasRings: false,
  cloudCount: 40,
  volcanicActivity: 0.3,
  waterHeight: 0.65,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#0A3B5B",
    beach: "#D8C596",
    regular: "#4D7F3A",
    mountain: "#8B7355",
  },
  landmarks: [
    {
      classification_id: "LM-101",
      type: "Mountain Range",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: 0.5, y: 0.8, z: 0.3 },
      influence_type: "mountain",
      influence_radius: 0.5,
      influence_strength: 0.7,
      influence_roughness: 0.5,
      category: "terrestrial",
    },
    {
      classification_id: "LM-102",
      type: "Ocean Basin",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: -0.3, y: -0.2, z: 0.7 },
      influence_type: "basin",
      influence_radius: 0.6,
      influence_strength: 0.5,
      influence_roughness: 0.2,
      category: "terrestrial",
    },
  ],
}

export const coruscantConfig = {
  mass: 1.1,
  radius: 1.05,
  temperature: 295,
  surfaceRoughness: 0.3,
  terrainErosion: 0.1,
  waterLevel: 0.4,
  biomassLevel: 0.1,
  plateTectonics: 0.2,
  soilType: "rocky",
  soilTexture: "layered",
  atmosphereStrength: 0.7,
  liquidType: "water",
  salinity: 0.2,
  precipitationCompound: "water",
  biome: "Urban Metropolis",
  mountainHeight: 0.4,
  hasRings: false,
  cloudCount: 25,
  volcanicActivity: 0.1,
  waterHeight: 0.4,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#1A2E3B",
    beach: "#5A5A5A",
    regular: "#8A8A8A",
    mountain: "#CCCCCC",
  },
  landmarks: [
    {
      classification_id: "LM-201",
      type: "Urban Center",
      visual_effect: "Light Emission",
      image_link: "",
      coordinates: { x: 0.2, y: 0.7, z: 0.5 },
      influence_type: "mountain",
      influence_radius: 0.8,
      influence_strength: 0.3,
      influence_roughness: 0.1,
      category: "terrestrial",
    },
    {
      classification_id: "LM-202",
      type: "Industrial Zone",
      visual_effect: "Smoke",
      image_link: "",
      coordinates: { x: -0.5, y: 0.3, z: 0.6 },
      influence_type: "basin",
      influence_radius: 0.4,
      influence_strength: 0.2,
      influence_roughness: 0.3,
      category: "terrestrial",
    },
  ],
}

export const nubiaConfig = {
  mass: 0.9,
  radius: 0.95,
  temperature: 300,
  surfaceRoughness: 0.7,
  terrainErosion: 0.5,
  waterLevel: 0.55,
  biomassLevel: 0.8,
  plateTectonics: 0.9,
  soilType: "organic",
  soilTexture: "crystalline",
  atmosphereStrength: 0.85,
  liquidType: "water",
  salinity: 0.3,
  precipitationCompound: "water",
  biome: "Vibrant Highlands",
  mountainHeight: 0.65,
  hasRings: false,
  cloudCount: 20,
  volcanicActivity: 0.4,
  waterHeight: 0.55,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#1A9B8B",
    beach: "#D8E596",
    regular: "#9B4D7A",
    mountain: "#7F3A4D",
  },
  landmarks: [
    {
      classification_id: "LM-301",
      type: "Crystal Formation",
      visual_effect: "Light Refraction",
      image_link: "",
      coordinates: { x: 0.3, y: 0.6, z: 0.4 },
      influence_type: "mountain",
      influence_radius: 0.6,
      influence_strength: 0.7,
      influence_roughness: 0.3,
      category: "terrestrial",
    },
    {
      classification_id: "LM-302",
      type: "Colorful Plains",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: -0.4, y: -0.3, z: 0.5 },
      influence_type: "basin",
      influence_radius: 0.7,
      influence_strength: 0.4,
      influence_roughness: 0.2,
      category: "terrestrial",
    },
  ],
}

export const tatooineConfig = {
  mass: 0.8,
  radius: 0.9,
  temperature: 330,
  surfaceRoughness: 0.8,
  terrainErosion: 0.7,
  waterLevel: 0.1,
  biomassLevel: 0.1,
  plateTectonics: 0.3,
  soilType: "sandy",
  soilTexture: "grainy",
  atmosphereStrength: 0.5,
  liquidType: "water",
  salinity: 0.9,
  precipitationCompound: "none",
  biome: "Arid Desert",
  mountainHeight: 0.5,
  hasRings: false,
  cloudCount: 5,
  volcanicActivity: 0.1,
  waterHeight: 0.1,
  liquidEnabled: false,
  customColors: {
    oceanFloor: "#8B4513",
    beach: "#D2B48C",
    regular: "#DAA520",
    mountain: "#B8860B",
  },
  landmarks: [
    {
      classification_id: "LM-401",
      type: "Dune Sea",
      visual_effect: "Heat Haze",
      image_link: "",
      coordinates: { x: 0.5, y: 0.5, z: 0.5 },
      influence_type: "dune",
      influence_radius: 0.8,
      influence_strength: 0.9,
      influence_roughness: 0.7,
      category: "terrestrial",
    },
    {
      classification_id: "LM-402",
      type: "Canyon",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: -0.3, y: 0.4, z: 0.6 },
      influence_type: "valley",
      influence_radius: 0.5,
      influence_strength: 0.6,
      influence_roughness: 0.4,
      category: "terrestrial",
    },
  ],
}

export const nabooConfig = {
  mass: 1.05,
  radius: 1.02,
  temperature: 292,
  surfaceRoughness: 0.6,
  terrainErosion: 0.5,
  waterLevel: 0.7,
  biomassLevel: 0.9,
  plateTectonics: 0.7,
  soilType: "organic",
  soilTexture: "smooth",
  atmosphereStrength: 0.9,
  liquidType: "water",
  salinity: 0.25,
  precipitationCompound: "water",
  biome: "Lush Plains",
  mountainHeight: 0.6,
  hasRings: false,
  cloudCount: 35,
  volcanicActivity: 0.2,
  waterHeight: 0.7,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#0B4C5F",
    beach: "#F5DEB3",
    regular: "#228B22",
    mountain: "#556B2F",
  },
  landmarks: [
    {
      classification_id: "LM-501",
      type: "Lake District",
      visual_effect: "Mist",
      image_link: "",
      coordinates: { x: 0.4, y: 0.6, z: 0.3 },
      influence_type: "basin",
      influence_radius: 0.5,
      influence_strength: 0.6,
      influence_roughness: 0.2,
      category: "terrestrial",
    },
    {
      classification_id: "LM-502",
      type: "Grassland",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: -0.5, y: -0.2, z: 0.4 },
      influence_type: "basin",
      influence_radius: 0.7,
      influence_strength: 0.3,
      influence_roughness: 0.1,
      category: "terrestrial",
    },
  ],
}

export const mustafarConfig = {
  mass: 0.95,
  radius: 0.9,
  temperature: 450,
  surfaceRoughness: 0.9,
  terrainErosion: 0.3,
  waterLevel: 0.2,
  biomassLevel: 0.05,
  plateTectonics: 0.95,
  soilType: "volcanic",
  soilTexture: "cracked",
  atmosphereStrength: 0.7,
  liquidType: "none",
  salinity: 0,
  precipitationCompound: "none",
  biome: "Volcanic Wasteland",
  mountainHeight: 0.8,
  hasRings: false,
  cloudCount: 15,
  volcanicActivity: 0.95,
  waterHeight: 0.2,
  liquidEnabled: false,
  customColors: {
    oceanFloor: "#3B0000",
    beach: "#800000",
    regular: "#A52A2A",
    mountain: "#FF4500",
  },
  landmarks: [
    {
      classification_id: "LM-601",
      type: "Active Volcano",
      visual_effect: "Lava Flow",
      image_link: "",
      coordinates: { x: 0.6, y: 0.4, z: 0.5 },
      influence_type: "volcano",
      influence_radius: 0.7,
      influence_strength: 0.9,
      influence_roughness: 0.8,
      category: "terrestrial",
    },
    {
      classification_id: "LM-602",
      type: "Lava Field",
      visual_effect: "Heat Distortion",
      image_link: "",
      coordinates: { x: -0.4, y: 0.5, z: 0.3 },
      influence_type: "basin",
      influence_radius: 0.6,
      influence_strength: 0.7,
      influence_roughness: 0.6,
      category: "terrestrial",
    },
  ],
}

export const hothConfig = {
  mass: 0.85,
  radius: 0.9,
  temperature: 220,
  surfaceRoughness: 0.5,
  terrainErosion: 0.2,
  waterLevel: 0.3,
  biomassLevel: 0.05,
  plateTectonics: 0.4,
  soilType: "frozen",
  soilTexture: "crystalline",
  atmosphereStrength: 0.6,
  liquidType: "water",
  salinity: 0.1,
  precipitationCompound: "snow",
  biome: "Frigid Tundra",
  mountainHeight: 0.7,
  hasRings: false,
  cloudCount: 30,
  volcanicActivity: 0.05,
  waterHeight: 0.3,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#A5F2F3",
    beach: "#E0FFFF",
    regular: "#F0F8FF",
    mountain: "#FFFFFF",
  },
  landmarks: [
    {
      classification_id: "LM-701",
      type: "Glacier",
      visual_effect: "Aurora",
      image_link: "",
      coordinates: { x: 0.3, y: 0.7, z: 0.4 },
      influence_type: "glacier",
      influence_radius: 0.6,
      influence_strength: 0.8,
      influence_roughness: 0.3,
      category: "terrestrial",
    },
    {
      classification_id: "LM-702",
      type: "Ice Cave",
      visual_effect: "None",
      image_link: "",
      coordinates: { x: -0.5, y: 0.2, z: 0.6 },
      influence_type: "crater",
      influence_radius: 0.4,
      influence_strength: 0.5,
      influence_roughness: 0.2,
      category: "terrestrial",
    },
  ],
}

export const bespinConfig = {
  mass: 15,
  radius: 3.5,
  temperature: 320,
  surfaceRoughness: 0.3,
  terrainErosion: 0.1,
  waterLevel: 0,
  biomassLevel: 0,
  plateTectonics: 0,
  soilType: "gaseous",
  soilTexture: "smooth",
  atmosphereStrength: 1.0,
  liquidType: "none",
  salinity: 0,
  precipitationCompound: "none",
  biome: "Gas Giant",
  mountainHeight: 0.2,
  hasRings: false,
  cloudCount: 80,
  volcanicActivity: 0,
  waterHeight: 0,
  liquidEnabled: false,
  customColors: {
    oceanFloor: "#FF7F50",
    beach: "#FFA07A",
    regular: "#FFD700",
    mountain: "#FAFAD2",
  },
  landmarks: [
    {
      classification_id: "LM-801",
      type: "Storm System",
      visual_effect: "Turbulence",
      image_link: "",
      coordinates: { x: 0.5, y: 0.5, z: 0.5 },
      influence_type: "storm",
      influence_radius: 0.9,
      influence_strength: 0.8,
      influence_roughness: 0.4,
      category: "gaseous",
    },
    {
      classification_id: "LM-802",
      type: "Cloud City",
      visual_effect: "Light Emission",
      image_link: "",
      coordinates: { x: -0.3, y: 0.6, z: 0.4 },
      influence_type: "spot",
      influence_radius: 0.3,
      influence_strength: 0.5,
      influence_roughness: 0.2,
      category: "gaseous",
    },
  ],
}

export const kaminoConfig = {
  mass: 1.1,
  radius: 1.05,
  temperature: 295,
  surfaceRoughness: 0.4,
  terrainErosion: 0.7,
  waterLevel: 0.95,
  biomassLevel: 0.3,
  plateTectonics: 0.6,
  soilType: "rocky",
  soilTexture: "smooth",
  atmosphereStrength: 0.9,
  liquidType: "water",
  salinity: 0.4,
  precipitationCompound: "water",
  biome: "Oceanic",
  mountainHeight: 0.5,
  hasRings: false,
  cloudCount: 60,
  volcanicActivity: 0.2,
  waterHeight: 0.95,
  liquidEnabled: true,
  customColors: {
    oceanFloor: "#00008B",
    beach: "#87CEEB",
    regular: "#B0E0E6",
    mountain: "#F5F5F5",
  },
  landmarks: [
    {
      classification_id: "LM-901",
      type: "Oceanic Platform",
      visual_effect: "Rain",
      image_link: "",
      coordinates: { x: 0.4, y: 0.6, z: 0.5 },
      influence_type: "mountain",
      influence_radius: 0.3,
      influence_strength: 0.9,
      influence_roughness: 0.2,
      category: "terrestrial",
    },
    {
      classification_id: "LM-902",
      type: "Storm System",
      visual_effect: "Lightning",
      image_link: "",
      coordinates: { x: -0.5, y: 0.3, z: 0.6 },
      influence_type: "storm",
      influence_radius: 0.7,
      influence_strength: 0.8,
      influence_roughness: 0.5,
      category: "gaseous",
    },
  ],
}
